apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: 078346402895.dkr.ecr.ap-south-1.amazonaws.com/backend:latest
          resources:
            requests:
              cpu: "10m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "500Mi"
          ports:
            - containerPort: 3001
          command:
            - npm start


