apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: postgres-master
spec:
  template:
    metadata:
      labels:
        app: postgres-master
    spec:
      containers:
        - name: postgres-master
          image: postgres:11.2-alpine
          ports:
            - containerPort: 5432
          env:  # TODO: Use configmap/secrets
            - name: POSTGRES_PASSWORD
              value: "password"
            - name: POSTGRES_DB
              value: "demo-db"
